version: '3.2'
services:
    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        container_name: 'rabbitmq'
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - ~/.docker/rabbitmq/data:/var/lib/rabbitmq/
            - ~/.docker/rabbitmq/log:/var/log/rabbitmq
        networks:
            - rabbitmq_network

    consumer:
        build:
            context: ./
            dockerfile: Dockerfile
            target: development
        volumes:
            - .:/app
        depends_on:
            - rabbitmq
        command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node dist/consumer.js'
        environment:
            NODE_ENV: production
            AMQP_URL: amqp://guest:guest@rabbitmq:5672
        networks:
            - rabbitmq_network

networks:
    rabbitmq_network:
        driver: bridge
# docker-compose exec consumer /bin/bash -c 'for ((i=1;i<=15;i++)); do node publisher.js; done'
